version: "3"
services:
    tingtong_web_student:
        image: registry.gitlab.com/online-learning-hcmus/client/tingtong:staging
        container_name: tingtong_web_student
        restart: always
        ports:
            - "80:3000"

networks:
    default:
        external:
            name: tingtong_network
